# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bio_ik_msgs/ConeGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class ConeGoal(genpy.Message):
  _md5sum = "d627f3360ed70a33e1852aae499c94db"
  _type = "bio_ik_msgs/ConeGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# The name of this goal's end effector link
string link_name

# Weight of the current goal
# Goals with a higher weight will have a stronger influence than goals with a smaller weight
float64 weight

geometry_msgs/Point position
float64 position_weight
geometry_msgs/Vector3 axis
geometry_msgs/Vector3 direction
float64 angle

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['link_name','weight','position','position_weight','axis','direction','angle']
  _slot_types = ['string','float64','geometry_msgs/Point','float64','geometry_msgs/Vector3','geometry_msgs/Vector3','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       link_name,weight,position,position_weight,axis,direction,angle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ConeGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.link_name is None:
        self.link_name = ''
      if self.weight is None:
        self.weight = 0.
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.position_weight is None:
        self.position_weight = 0.
      if self.axis is None:
        self.axis = geometry_msgs.msg.Vector3()
      if self.direction is None:
        self.direction = geometry_msgs.msg.Vector3()
      if self.angle is None:
        self.angle = 0.
    else:
      self.link_name = ''
      self.weight = 0.
      self.position = geometry_msgs.msg.Point()
      self.position_weight = 0.
      self.axis = geometry_msgs.msg.Vector3()
      self.direction = geometry_msgs.msg.Vector3()
      self.angle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.link_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_12d().pack(_x.weight, _x.position.x, _x.position.y, _x.position.z, _x.position_weight, _x.axis.x, _x.axis.y, _x.axis.z, _x.direction.x, _x.direction.y, _x.direction.z, _x.angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.axis is None:
        self.axis = geometry_msgs.msg.Vector3()
      if self.direction is None:
        self.direction = geometry_msgs.msg.Vector3()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.link_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.link_name = str[start:end]
      _x = self
      start = end
      end += 96
      (_x.weight, _x.position.x, _x.position.y, _x.position.z, _x.position_weight, _x.axis.x, _x.axis.y, _x.axis.z, _x.direction.x, _x.direction.y, _x.direction.z, _x.angle,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.link_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_12d().pack(_x.weight, _x.position.x, _x.position.y, _x.position.z, _x.position_weight, _x.axis.x, _x.axis.y, _x.axis.z, _x.direction.x, _x.direction.y, _x.direction.z, _x.angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.axis is None:
        self.axis = geometry_msgs.msg.Vector3()
      if self.direction is None:
        self.direction = geometry_msgs.msg.Vector3()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.link_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.link_name = str[start:end]
      _x = self
      start = end
      end += 96
      (_x.weight, _x.position.x, _x.position.y, _x.position.z, _x.position_weight, _x.axis.x, _x.axis.y, _x.axis.z, _x.direction.x, _x.direction.y, _x.direction.z, _x.angle,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12d = None
def _get_struct_12d():
    global _struct_12d
    if _struct_12d is None:
        _struct_12d = struct.Struct("<12d")
    return _struct_12d
