# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bio_ik_msgs/JointVariableGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class JointVariableGoal(genpy.Message):
  _md5sum = "ee6ea02a53bfdacf34c1c1097ce15d71"
  _type = "bio_ik_msgs/JointVariableGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# The name of the joint variable
string variable_name

# The desired position value of the joint variable
float64 variable_position

# Weight of the current goal
# Goals with a higher weight will have a stronger influence than goals with a smaller weight
float64 weight

# If set to false, the goal will be primary goal (like eg. position goals)
# If set to true, this goal will always have lower priority than the primary goals
bool secondary
"""
  __slots__ = ['variable_name','variable_position','weight','secondary']
  _slot_types = ['string','float64','float64','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       variable_name,variable_position,weight,secondary

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(JointVariableGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.variable_name is None:
        self.variable_name = ''
      if self.variable_position is None:
        self.variable_position = 0.
      if self.weight is None:
        self.weight = 0.
      if self.secondary is None:
        self.secondary = False
    else:
      self.variable_name = ''
      self.variable_position = 0.
      self.weight = 0.
      self.secondary = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.variable_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2dB().pack(_x.variable_position, _x.weight, _x.secondary))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.variable_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.variable_name = str[start:end]
      _x = self
      start = end
      end += 17
      (_x.variable_position, _x.weight, _x.secondary,) = _get_struct_2dB().unpack(str[start:end])
      self.secondary = bool(self.secondary)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.variable_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2dB().pack(_x.variable_position, _x.weight, _x.secondary))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.variable_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.variable_name = str[start:end]
      _x = self
      start = end
      end += 17
      (_x.variable_position, _x.weight, _x.secondary,) = _get_struct_2dB().unpack(str[start:end])
      self.secondary = bool(self.secondary)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2dB = None
def _get_struct_2dB():
    global _struct_2dB
    if _struct_2dB is None:
        _struct_2dB = struct.Struct("<2dB")
    return _struct_2dB
