// Generated by gencpp from file fsc/SetV.msg
// DO NOT EDIT!


#ifndef FSC_MESSAGE_SETV_H
#define FSC_MESSAGE_SETV_H

#include <ros/service_traits.h>


#include <fsc/SetVRequest.h>
#include <fsc/SetVResponse.h>


namespace fsc
{

struct SetV
{

typedef SetVRequest Request;
typedef SetVResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetV
} // namespace fsc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fsc::SetV > {
  static const char* value()
  {
    return "8362ce87c5ed325fb041904db410063b";
  }

  static const char* value(const ::fsc::SetV&) { return value(); }
};

template<>
struct DataType< ::fsc::SetV > {
  static const char* value()
  {
    return "fsc/SetV";
  }

  static const char* value(const ::fsc::SetV&) { return value(); }
};


// service_traits::MD5Sum< ::fsc::SetVRequest> should match
// service_traits::MD5Sum< ::fsc::SetV >
template<>
struct MD5Sum< ::fsc::SetVRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fsc::SetV >::value();
  }
  static const char* value(const ::fsc::SetVRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fsc::SetVRequest> should match
// service_traits::DataType< ::fsc::SetV >
template<>
struct DataType< ::fsc::SetVRequest>
{
  static const char* value()
  {
    return DataType< ::fsc::SetV >::value();
  }
  static const char* value(const ::fsc::SetVRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fsc::SetVResponse> should match
// service_traits::MD5Sum< ::fsc::SetV >
template<>
struct MD5Sum< ::fsc::SetVResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fsc::SetV >::value();
  }
  static const char* value(const ::fsc::SetVResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fsc::SetVResponse> should match
// service_traits::DataType< ::fsc::SetV >
template<>
struct DataType< ::fsc::SetVResponse>
{
  static const char* value()
  {
    return DataType< ::fsc::SetV >::value();
  }
  static const char* value(const ::fsc::SetVResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FSC_MESSAGE_SETV_H
