# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from FootstepControl/MyState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MyState(genpy.Message):
  _md5sum = "4493873f0a72e816f885a561816cfc96"
  _type = "FootstepControl/MyState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 cx
float64 dcx
float64 cy
float64 dcy
uint8 is_left_support
uint8 is_right_support"""
  __slots__ = ['cx','dcx','cy','dcy','is_left_support','is_right_support']
  _slot_types = ['float64','float64','float64','float64','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cx,dcx,cy,dcy,is_left_support,is_right_support

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MyState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.cx is None:
        self.cx = 0.
      if self.dcx is None:
        self.dcx = 0.
      if self.cy is None:
        self.cy = 0.
      if self.dcy is None:
        self.dcy = 0.
      if self.is_left_support is None:
        self.is_left_support = 0
      if self.is_right_support is None:
        self.is_right_support = 0
    else:
      self.cx = 0.
      self.dcx = 0.
      self.cy = 0.
      self.dcy = 0.
      self.is_left_support = 0
      self.is_right_support = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4d2B().pack(_x.cx, _x.dcx, _x.cy, _x.dcy, _x.is_left_support, _x.is_right_support))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 34
      (_x.cx, _x.dcx, _x.cy, _x.dcy, _x.is_left_support, _x.is_right_support,) = _get_struct_4d2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4d2B().pack(_x.cx, _x.dcx, _x.cy, _x.dcy, _x.is_left_support, _x.is_right_support))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 34
      (_x.cx, _x.dcx, _x.cy, _x.dcy, _x.is_left_support, _x.is_right_support,) = _get_struct_4d2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d2B = None
def _get_struct_4d2B():
    global _struct_4d2B
    if _struct_4d2B is None:
        _struct_4d2B = struct.Struct("<4d2B")
    return _struct_4d2B
