// Generated by gencpp from file FootstepControl/SetVResponse.msg
// DO NOT EDIT!


#ifndef FOOTSTEPCONTROL_MESSAGE_SETVRESPONSE_H
#define FOOTSTEPCONTROL_MESSAGE_SETVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace FootstepControl
{
template <class ContainerAllocator>
struct SetVResponse_
{
  typedef SetVResponse_<ContainerAllocator> Type;

  SetVResponse_()
    {
    }
  SetVResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::FootstepControl::SetVResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::FootstepControl::SetVResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetVResponse_

typedef ::FootstepControl::SetVResponse_<std::allocator<void> > SetVResponse;

typedef boost::shared_ptr< ::FootstepControl::SetVResponse > SetVResponsePtr;
typedef boost::shared_ptr< ::FootstepControl::SetVResponse const> SetVResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::FootstepControl::SetVResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::FootstepControl::SetVResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace FootstepControl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::FootstepControl::SetVResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::FootstepControl::SetVResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::FootstepControl::SetVResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::FootstepControl::SetVResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::FootstepControl::SetVResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::FootstepControl::SetVResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::FootstepControl::SetVResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::FootstepControl::SetVResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::FootstepControl::SetVResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "FootstepControl/SetVResponse";
  }

  static const char* value(const ::FootstepControl::SetVResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::FootstepControl::SetVResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::FootstepControl::SetVResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::FootstepControl::SetVResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetVResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::FootstepControl::SetVResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::FootstepControl::SetVResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FOOTSTEPCONTROL_MESSAGE_SETVRESPONSE_H
