// Generated by gencpp from file FootstepControl/SetVRequest.msg
// DO NOT EDIT!


#ifndef FOOTSTEPCONTROL_MESSAGE_SETVREQUEST_H
#define FOOTSTEPCONTROL_MESSAGE_SETVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace FootstepControl
{
template <class ContainerAllocator>
struct SetVRequest_
{
  typedef SetVRequest_<ContainerAllocator> Type;

  SetVRequest_()
    : vx(0.0)
    , vy(0.0)
    , vr(0.0)  {
    }
  SetVRequest_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , vy(0.0)
    , vr(0.0)  {
  (void)_alloc;
    }



   typedef double _vx_type;
  _vx_type vx;

   typedef double _vy_type;
  _vy_type vy;

   typedef double _vr_type;
  _vr_type vr;





  typedef boost::shared_ptr< ::FootstepControl::SetVRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::FootstepControl::SetVRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetVRequest_

typedef ::FootstepControl::SetVRequest_<std::allocator<void> > SetVRequest;

typedef boost::shared_ptr< ::FootstepControl::SetVRequest > SetVRequestPtr;
typedef boost::shared_ptr< ::FootstepControl::SetVRequest const> SetVRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::FootstepControl::SetVRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::FootstepControl::SetVRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::FootstepControl::SetVRequest_<ContainerAllocator1> & lhs, const ::FootstepControl::SetVRequest_<ContainerAllocator2> & rhs)
{
  return lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy &&
    lhs.vr == rhs.vr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::FootstepControl::SetVRequest_<ContainerAllocator1> & lhs, const ::FootstepControl::SetVRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace FootstepControl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::FootstepControl::SetVRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::FootstepControl::SetVRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::FootstepControl::SetVRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::FootstepControl::SetVRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::FootstepControl::SetVRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::FootstepControl::SetVRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::FootstepControl::SetVRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8362ce87c5ed325fb041904db410063b";
  }

  static const char* value(const ::FootstepControl::SetVRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8362ce87c5ed325fULL;
  static const uint64_t static_value2 = 0xb041904db410063bULL;
};

template<class ContainerAllocator>
struct DataType< ::FootstepControl::SetVRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "FootstepControl/SetVRequest";
  }

  static const char* value(const ::FootstepControl::SetVRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::FootstepControl::SetVRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 vx\n"
"float64 vy\n"
"float64 vr\n"
;
  }

  static const char* value(const ::FootstepControl::SetVRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::FootstepControl::SetVRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetVRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::FootstepControl::SetVRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::FootstepControl::SetVRequest_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    s << indent << "vr: ";
    Printer<double>::stream(s, indent + "  ", v.vr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOOTSTEPCONTROL_MESSAGE_SETVREQUEST_H
