// Generated by gencpp from file bio_ik_msgs/CenterJointsGoal.msg
// DO NOT EDIT!


#ifndef BIO_IK_MSGS_MESSAGE_CENTERJOINTSGOAL_H
#define BIO_IK_MSGS_MESSAGE_CENTERJOINTSGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bio_ik_msgs
{
template <class ContainerAllocator>
struct CenterJointsGoal_
{
  typedef CenterJointsGoal_<ContainerAllocator> Type;

  CenterJointsGoal_()
    : weight(0.0)
    , primary(false)  {
    }
  CenterJointsGoal_(const ContainerAllocator& _alloc)
    : weight(0.0)
    , primary(false)  {
  (void)_alloc;
    }



   typedef double _weight_type;
  _weight_type weight;

   typedef uint8_t _primary_type;
  _primary_type primary;





  typedef boost::shared_ptr< ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CenterJointsGoal_

typedef ::bio_ik_msgs::CenterJointsGoal_<std::allocator<void> > CenterJointsGoal;

typedef boost::shared_ptr< ::bio_ik_msgs::CenterJointsGoal > CenterJointsGoalPtr;
typedef boost::shared_ptr< ::bio_ik_msgs::CenterJointsGoal const> CenterJointsGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator1> & lhs, const ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator2> & rhs)
{
  return lhs.weight == rhs.weight &&
    lhs.primary == rhs.primary;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator1> & lhs, const ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bio_ik_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ccbc658a4d415bcd21aba09a68bf23dd";
  }

  static const char* value(const ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xccbc658a4d415bcdULL;
  static const uint64_t static_value2 = 0x21aba09a68bf23ddULL;
};

template<class ContainerAllocator>
struct DataType< ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bio_ik_msgs/CenterJointsGoal";
  }

  static const char* value(const ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Weight of the current goal\n"
"# Goals with a higher weight will have a stronger influence than goals with a smaller weight\n"
"float64 weight\n"
"\n"
"# If set to true, the goal will be primary goal (like eg. position goals)\n"
"# If set to false, this goal will always have lower priority than the primary goals\n"
"bool primary\n"
;
  }

  static const char* value(const ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.weight);
      stream.next(m.primary);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CenterJointsGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bio_ik_msgs::CenterJointsGoal_<ContainerAllocator>& v)
  {
    s << indent << "weight: ";
    Printer<double>::stream(s, indent + "  ", v.weight);
    s << indent << "primary: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.primary);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIO_IK_MSGS_MESSAGE_CENTERJOINTSGOAL_H
