// Generated by gencpp from file bio_ik_msgs/LookAtGoal.msg
// DO NOT EDIT!


#ifndef BIO_IK_MSGS_MESSAGE_LOOKATGOAL_H
#define BIO_IK_MSGS_MESSAGE_LOOKATGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Point.h>

namespace bio_ik_msgs
{
template <class ContainerAllocator>
struct LookAtGoal_
{
  typedef LookAtGoal_<ContainerAllocator> Type;

  LookAtGoal_()
    : link_name()
    , weight(0.0)
    , axis()
    , target()  {
    }
  LookAtGoal_(const ContainerAllocator& _alloc)
    : link_name(_alloc)
    , weight(0.0)
    , axis(_alloc)
    , target(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _link_name_type;
  _link_name_type link_name;

   typedef double _weight_type;
  _weight_type weight;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _axis_type;
  _axis_type axis;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _target_type;
  _target_type target;





  typedef boost::shared_ptr< ::bio_ik_msgs::LookAtGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bio_ik_msgs::LookAtGoal_<ContainerAllocator> const> ConstPtr;

}; // struct LookAtGoal_

typedef ::bio_ik_msgs::LookAtGoal_<std::allocator<void> > LookAtGoal;

typedef boost::shared_ptr< ::bio_ik_msgs::LookAtGoal > LookAtGoalPtr;
typedef boost::shared_ptr< ::bio_ik_msgs::LookAtGoal const> LookAtGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bio_ik_msgs::LookAtGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bio_ik_msgs::LookAtGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bio_ik_msgs::LookAtGoal_<ContainerAllocator1> & lhs, const ::bio_ik_msgs::LookAtGoal_<ContainerAllocator2> & rhs)
{
  return lhs.link_name == rhs.link_name &&
    lhs.weight == rhs.weight &&
    lhs.axis == rhs.axis &&
    lhs.target == rhs.target;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bio_ik_msgs::LookAtGoal_<ContainerAllocator1> & lhs, const ::bio_ik_msgs::LookAtGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bio_ik_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::bio_ik_msgs::LookAtGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bio_ik_msgs::LookAtGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bio_ik_msgs::LookAtGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bio_ik_msgs::LookAtGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bio_ik_msgs::LookAtGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bio_ik_msgs::LookAtGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bio_ik_msgs::LookAtGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5353e403e5f3d793ed695b9d5f62178a";
  }

  static const char* value(const ::bio_ik_msgs::LookAtGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5353e403e5f3d793ULL;
  static const uint64_t static_value2 = 0xed695b9d5f62178aULL;
};

template<class ContainerAllocator>
struct DataType< ::bio_ik_msgs::LookAtGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bio_ik_msgs/LookAtGoal";
  }

  static const char* value(const ::bio_ik_msgs::LookAtGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bio_ik_msgs::LookAtGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The name of this goal's end effector link\n"
"string link_name\n"
"\n"
"# Weight of the current goal\n"
"# Goals with a higher weight will have a stronger influence than goals with a smaller weight\n"
"float64 weight\n"
"\n"
"# The axis in the link's local coordinate frame which shall point towards the target\n"
"geometry_msgs/Vector3 axis\n"
"\n"
"# The target point which the axis shall point at\n"
"geometry_msgs/Point target\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::bio_ik_msgs::LookAtGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bio_ik_msgs::LookAtGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.link_name);
      stream.next(m.weight);
      stream.next(m.axis);
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LookAtGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bio_ik_msgs::LookAtGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bio_ik_msgs::LookAtGoal_<ContainerAllocator>& v)
  {
    s << indent << "link_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.link_name);
    s << indent << "weight: ";
    Printer<double>::stream(s, indent + "  ", v.weight);
    s << indent << "axis: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.axis);
    s << indent << "target: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIO_IK_MSGS_MESSAGE_LOOKATGOAL_H
