// Generated by gencpp from file bio_ik_msgs/PositionGoal.msg
// DO NOT EDIT!


#ifndef BIO_IK_MSGS_MESSAGE_POSITIONGOAL_H
#define BIO_IK_MSGS_MESSAGE_POSITIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace bio_ik_msgs
{
template <class ContainerAllocator>
struct PositionGoal_
{
  typedef PositionGoal_<ContainerAllocator> Type;

  PositionGoal_()
    : link_name()
    , weight(0.0)
    , position()  {
    }
  PositionGoal_(const ContainerAllocator& _alloc)
    : link_name(_alloc)
    , weight(0.0)
    , position(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _link_name_type;
  _link_name_type link_name;

   typedef double _weight_type;
  _weight_type weight;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::bio_ik_msgs::PositionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bio_ik_msgs::PositionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PositionGoal_

typedef ::bio_ik_msgs::PositionGoal_<std::allocator<void> > PositionGoal;

typedef boost::shared_ptr< ::bio_ik_msgs::PositionGoal > PositionGoalPtr;
typedef boost::shared_ptr< ::bio_ik_msgs::PositionGoal const> PositionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bio_ik_msgs::PositionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bio_ik_msgs::PositionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bio_ik_msgs::PositionGoal_<ContainerAllocator1> & lhs, const ::bio_ik_msgs::PositionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.link_name == rhs.link_name &&
    lhs.weight == rhs.weight &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bio_ik_msgs::PositionGoal_<ContainerAllocator1> & lhs, const ::bio_ik_msgs::PositionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bio_ik_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::bio_ik_msgs::PositionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bio_ik_msgs::PositionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bio_ik_msgs::PositionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bio_ik_msgs::PositionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bio_ik_msgs::PositionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bio_ik_msgs::PositionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bio_ik_msgs::PositionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7ba9cf3694b741fc17857a4a52dcde9";
  }

  static const char* value(const ::bio_ik_msgs::PositionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7ba9cf3694b741fULL;
  static const uint64_t static_value2 = 0xc17857a4a52dcde9ULL;
};

template<class ContainerAllocator>
struct DataType< ::bio_ik_msgs::PositionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bio_ik_msgs/PositionGoal";
  }

  static const char* value(const ::bio_ik_msgs::PositionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bio_ik_msgs::PositionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The name of this goal's end effector link\n"
"string link_name\n"
"\n"
"# Weight of the current goal\n"
"# Goals with a higher weight will have a stronger influence than goals with a smaller weight\n"
"float64 weight\n"
"\n"
"# The goal position into which the end effector link shall be brought\n"
"geometry_msgs/Point position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::bio_ik_msgs::PositionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bio_ik_msgs::PositionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.link_name);
      stream.next(m.weight);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bio_ik_msgs::PositionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bio_ik_msgs::PositionGoal_<ContainerAllocator>& v)
  {
    s << indent << "link_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.link_name);
    s << indent << "weight: ";
    Printer<double>::stream(s, indent + "  ", v.weight);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIO_IK_MSGS_MESSAGE_POSITIONGOAL_H
